### ISSUE TITLE
Demo2 can't be runned

### ISSUE THREAD

**Issue by SongZhuhai** [KieranWynn/pyquaternion#18]
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\projections\__init__.py", line 63, in get_projection_class
    return projection_registry.get_projection_class(projection)
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\projections\__init__.py", line 29, in get_projection_class
    return self._all_projection_types[name]
KeyError: '3d'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\工作空间\L\Python\pyquaternion\2.py", line 51, in <module>
    ax = fig.add_axes([0, 0, 1, 1], projection='3d')
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\figure.py", line 1126, in add_axes
    self, *args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\projections\__init__.py", line 91, in process_projection_requirements
    projection_class = get_projection_class(projection)
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\projections\__init__.py", line 65, in get_projection_class
    raise ValueError("Unknown projection '%s'" % projection)
ValueError: Unknown projection '3d'

**Comment by SongZhuhai** [comment]
The problem has solved:

from mpl_toolkits.mplot3d import axes3d, Axes3D

ax = Axes3D(fig)
##ax = fig.add_axes([0, 0, 1, 1], projection='3d')
